version: "3.9"

services:
  db:
    image: mariadb:10.5
    container_name: nicaxel-db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: nicaxel
      MYSQL_USER: nicouser
      MYSQL_PASSWORD: SuperClave123!
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nicaxel-net

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/nicaxel
      SPRING_DATASOURCE_USERNAME: nicouser
      SPRING_DATASOURCE_PASSWORD: SuperClave123!
    depends_on:
      - db
    networks:
      - nicaxel-net

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/nicaxel
      SPRING_DATASOURCE_USERNAME: nicouser
      SPRING_DATASOURCE_PASSWORD: SuperClave123!
    depends_on:
      - db
    networks:
      - nicaxel-net

  cart-service:
    build:
      context: ./cart-service
    container_name: cart-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/nicaxel
      SPRING_DATASOURCE_USERNAME: nicouser
      SPRING_DATASOURCE_PASSWORD: SuperClave123!
    depends_on:
      - db
      - product-service
      - user-service
    networks:
      - nicaxel-net

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://98.93.39.249:8080
      - VITE_USER_API_URL=http://98.93.39.249:8081
      - VITE_CART_API_URL=http://98.93.39.249:8082
    depends_on:
      - product-service
      - user-service
      - cart-service
    networks:
      - nicaxel-net

networks:
  nicaxel-net:
    driver: bridge

volumes:
  mysql-data:
