version: "3.9"

services:
  backend:
    build:
      context: ./product-service
    container_name: nicaxel-backend
    ports:
      - "8080:8080"
    networks:
      - nicaxel-net

  user-service:
    build:
      context: ./user-service
    container_name: nicaxel-user-service
    ports:
      - "8081:8081"
    volumes:
      - user-data:/data
    networks:
      - nicaxel-net

  cart-service:
    build:
      context: ./cart-service
    container_name: nicaxel-cart-service
    ports:
      - "8082:8082"
    depends_on:
      - backend
      - user-service
    networks:
      - nicaxel-net

  frontend:
    build:
      context: ./frontend
    container_name: nicaxel-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - user-service
      - cart-service
    environment:
      - VITE_API_URL=http://backend:8080
      - VITE_USER_API_URL=http://user-service:8081
      - VITE_CART_API_URL=http://cart-service:8082
    networks:
      - nicaxel-net

networks:
  nicaxel-net:
    driver: bridge

volumes:
  user-data: