# Puerto del user-service
server.port=8081

spring.application.name=user-service

spring.datasource.url=jdbc:mysql://13.217.221.204:3306/nicaxel?useSSL=false&serverTimezone=UTC
spring.datasource.username=nicouser
spring.datasource.password=SuperClave123!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# JWT
jwt.secret=yuJHDJShd9238hds8dhs82hds829hd289hd2hhd829hd8HDSAUIHDSA08HD8asd8A==
jwt.expiration=3600000
