spring.application.name=product

spring.datasource.url=jdbc:mysql://13.217.221.204:3306/nicaxel?useSSL=false&serverTimezone=UTC
spring.datasource.username=nicouser
spring.datasource.password=SuperClave123!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



spring.jpa.defer-datasource-initialization=true



